# Generated by Django 3.1.1 on 2020-09-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_content',
            field=models.CharField(max_length=1000),
        ),
    ]
